feat(setuptools): specific var for python_requires
NotANameServer/incipyt pull request #32
Opened 2022-05-26 19:00 UTC by Julien00859

The PYTHON_VERSION is the python version currently in use, it does not
necessary correspond to the minimal python version that'll be supported
for the project. One can use py3.10 on his system (latest python as of
2022) but want his project to be compatible with py3.9 (as packaged in
debian bulleyes). This commit changes the variable to
AUDIENCE_PYTHON_VERSION which better reflect the purpose of the
variable.

---

## chore(setuptools): bump audience py version to 3.9

As of the 26 of May 2022, the version of the python package in major
distributions are:

alpine: 3.9
Arch Linux: 3.10
CentOS 9: 3.9
Debian bulleye: 3.9
Fedora 36: 3.10
FreeBSD: 3.10
gentoo: 3.10
openSUSE Tumbleweed: 3.10
Ubuntu jammy: 3.10
slackware 15: 3.9

2022-05-27 20:49 UTC, fblanchetNaN requested changes

2022-05-27 20:49 UTC, fblanchetNaN commented on incipyt/tools/setuptools.py
> +                AUDIENCE_PYTHON_VERSION=audience_version(),
As we only need that function here, we can also do:
```suggestion
                AUDIENCE_PYTHON_VERSION="{0[0]}.{0[1]}".format(min(sys.version_info, (3, 9))),  # noqa: FS002
```
I don't think we need that anywhere else.

2022-05-28 10:44 UTC, Julien00859 commented on incipyt/tools/setuptools.py
> +    return "{0[0]}.{0[1]}".format(min(sys.version_info, linux_version))  # noqa: FS002
Because 3.9 is a magic number, magic numbers are bad

2022-05-28 11:07 UTC, fblanchetNaN commented on incipyt/tools/setuptools.py
> +    return "{0[0]}.{0[1]}".format(min(sys.version_info, linux_version))  # noqa: FS002
I agree, but here it's purely local and you have a comment just above so it doesn't seem so bad to me.

2022-05-28 14:17 UTC, fblanchetNaN approved these changes

2022-05-28 14:17 UTC, merged